language:
 - gcc
 - clang
before_install:
 - pip install --user cpp-coveralls # --use-mirrors
 - sudo apt-get install valgrind
script:
 - make travis-check
after_success:
 - bash <(curl -s https://codecov.io/bash)
